
-- PADRÃO: 
-- [NOME DO CAMPO] [TIPO DO CAMPO] (TAMANHO)

CREATE TABLE [NOME DA TABELA]
([NOME DO CAMPO 1] [VARCHAR] (11) ,
[NOME DO CAMPO 2] [VARCHAR] (100) ,
[NOME DO CAMPO 3] [DATE],
[NOME DO CAMPO 4] [SMALLINT],
[NOME DO CAMPO 5] [VARCHAR] (1) ,
[NOME DO CAMPO 6] [MONEY] ,
[NOME DO CAMPO 7] [FLOAT] ,
[NOME DO CAMPO 8] [BIT] )
